name: coverup
title: CoverUP PDF
summary: A simple tool for redacting PDFs and images
description: |
  CoverUP is a privacy-focused tool for redacting sensitive information in PDF
  documents and images. Users can import PDF documents, which are converted into
  images during the process. This conversion ensures that text cannot be copied
  or indexed without OCR, enhancing the security of your information.

  Key features:
  - Import PDF, PNG, and JPG files
  - Draw black or white redaction bars over sensitive content
  - Invisible PDF layers are not converted, preventing accidental leaks
  - High-quality and compressed export modes
  - Session persistence - continue where you left off
  - Password-protected PDF support
  - Command-line file opening support

version: '0.4.0'
license: GPL-3.0
grade: stable
confinement: strict
base: core24

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  coverup:
    command: bin/coverup
    desktop: share/applications/coverup.desktop
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - x11
      - wayland
      - desktop
      - desktop-legacy

parts:
  coverup:
    plugin: python
    source: https://github.com/digidigital/CoverUP.git
    source-type: git
    source-tag: v0.4.0
    python-requirements:
      - requirements.txt
    stage-packages:
      - python3-tk
      - python3-pil
      - python3-pil.imagetk
      - libxcb-xtest0
      - libpython3.12-stdlib
      - libpython3.12-minimal
    build-packages:
      - python3-dev
      - python3-pip
      - python3-setuptools
      - python3-venv
    override-build: |
      craftctl default

      # Create desktop file
      mkdir -p $CRAFT_PART_INSTALL/share/applications
      cat > $CRAFT_PART_INSTALL/share/applications/coverup.desktop << 'EOF'
      [Desktop Entry]
      Name=CoverUP PDF
      GenericName=PDF Redaction Tool
      Comment=Redact sensitive information in PDFs and images
      Exec=coverup %f
      Icon=${SNAP}/share/icons/coverup.svg
      Terminal=false
      Type=Application
      Categories=Office;Utility;Graphics;
      MimeType=application/pdf;image/png;image/jpeg;
      StartupNotify=true
      Keywords=pdf;redact;privacy;censor;black;bar;
      EOF

      # Create icon directory and copy icon
      mkdir -p $CRAFT_PART_INSTALL/share/icons
      if [ -f $CRAFT_PART_SRC/CoverUP.ico ]; then
        cp $CRAFT_PART_SRC/CoverUP.ico $CRAFT_PART_INSTALL/share/icons/coverup.ico
      fi
      if [ -f $CRAFT_PART_SRC/CoverUP.svg ]; then
        cp $CRAFT_PART_SRC/CoverUP.svg $CRAFT_PART_INSTALL/share/icons/coverup.svg
      fi
